### ISSUE TITLE
[BUG] IMOD 4.10 download not available anymore and 4.9.12 and 4.11.24 give errors

### ISSUE THREAD

**Issue by wlugmayr** [KudryashevLab/TomoBEAR#20] opened 2023-05-22 14:30 UTC
**Describe the bug**

You recommend imod 4.10.42 or earlier on your install instructions.
imod 4.11.24 gives the error described in bug #18 and imod 4.9.12 gives an autofidseed error as described below.

**Project JSON file**

```JSON
ribosome_empiar_10064_dynamo.json
```

**Error message**
:
Making coarse aligned stack (running prenewst.com)   [brt2]
Successfully finished prenewst.com   in 00:07.2   [brt3]

Finding seed points for fiducial model (running autofidseed.com)   [brt2]
processchunks ERROR: autofidseed.com has given processing error 1 times - giving up
ERROR: autofidseed -StandardInput: exited with status 1
 
ABORT SET: An error occurred running autofidseed.com
:+1: 

$ cat output/5_BatchRunTomo_1/tomogram_001/autofidseed.log

*** Entries to program autofidseed ***
  TrackCommandFile = track.com
  MinSpacing = 0.85
  AdjustSizes = 1
  PeakStorageFraction = 1.0
  TwoSurfaces = 0
  TargetNumberOfBeads = 20
*** End of entries ***

RUNNING IMODFINDBEADS on views 30, 31, and 32
 
Scaling down by 1.07 for Sobel filter; box size = 32, scaled size = 29

Analyzing group of sections starting with 29, ending with 31
Dips found in 3 groups based on bkg mean, means 161.86 to 165.37
Pass 1: 16382 peaks found. 13225 eliminated as too weak, 174 too close, 2983 remaining
Histogram smoothed with H = 0.200 has dip at 0.307, peaks at 0.064 and 0.544
Histogram smoothed with H = 0.050 has lowest dip at 0.323
Threshold for averaging set to 0.378
Diameter of average bead at zero-crossing = 9.19
Adjusted parameters based on a new bead size of 9.19
Scaling down by 1.15 for Sobel filter; box size = 34, scaled size = 29
Adding another pass because size changed more than 5%
Dips found in 4 groups based on bkg mean, means 155.84 to 165.24
Pass 2: 20917 peaks found. 15861 eliminated as too weak, 926 too close, 4130 remaining
Histogram smoothed with H = 0.141 has dip at 0.494, peaks at 0.068 and 0.572
Histogram smoothed with H = 0.050 has lowest dip at 0.533
Threshold for averaging set to 0.543
Diameter of average bead at zero-crossing = 9.40
Adjusted parameters based on a new bead size of 9.40
Scaling down by 1.18 for Sobel filter; box size = 34, scaled size = 28
Dips found in 4 groups based on bkg mean, means 155.82 to 165.26
Pass 3: 20067 peaks found. 14911 eliminated as too weak, 999 too close, 4157 remaining
Histogram smoothed with H = 0.141 has dip at 0.549, peaks at 0.069 and 0.567
Histogram smoothed with H = 0.050 has lowest dip at 0.550
11 peaks are above histogram dip at 0.550
11 total peaks being stored in model down to value of 0.553
 
REDOING IMODFINDBEADS with more views to try to get more points
Traceback (most recent call last):
  File "/gpfs/cssb/software/centos7/x86_64/imod/4.9.12/bin/autofidseed", line 801, in <module>
    seedViews = selectSeedViews(numSeedViews)
  File "/gpfs/cssb/software/centos7/x86_64/imod/4.9.12/bin/autofidseed", line 196, in selectSeedViews
    viewTry = fillFirstGap(seedViews, checkDir, midZ)
  File "/gpfs/cssb/software/centos7/x86_64/imod/4.9.12/bin/autofidseed", line 52, in fillFirstGap
    trackRange = rangeLo + rangeHi
TypeError: unsupported operand type(s) for +: 'range' and 'range'
ERROR: autofidseed -StandardInput: exited with status 1

**To Reproduce**
Run the ribosome tutorial in MATLAB.

**Additional context**
This step runs with imod 4.11.24 but it fails like on #18

**Comment by ArtsemiY** [comment] 2023-05-23 13:42
@wlugmayr thanks for pointing to this!
We will check the reason for this issue in the nearest time.

**Comment by ArtsemiY** [comment] 2023-06-06 15:25
@wlugmayr
I installed imod-4.9.12 and re-runned tutorial, but could not reproduce the issue.
Please, let me know whether you have changed the path to the full one as in #18 and tried to reprocess from zero (since otherwise relative path which might cause the issue here as well could be saved in intermediate configuration files).

P.S. Please, let me know as well whether you are generally interested in resolving this issue after #18 was resolved or it might be withdrawn.

**Comment by ArtsemiY** [comment] 2023-06-09 07:07
Glad to hear! Thanks!

**Closed by ArtsemiY** 2023-06-09 07:07 UTC
Labels: pending
